# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='رقم المشروع')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المشروع')),
                ('project_type', models.CharField(choices=[('food', 'توزيع غذاء'), ('clothing', 'كسوة الشتاء'), ('water', 'سقيا المياه'), ('medical', 'دعم العلاج'), ('renovation', 'ترميم المنازل'), ('educational', 'مساعدات تعليمية'), ('seasonal', 'مساعدات موسمية'), ('iftar', 'إفطار صائم'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الهدف المالي')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الميزانية')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المنصرف')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('planning', 'تخطيط'), ('approved', 'معتمد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'منتهي'), ('cancelled', 'ملغي')], default='planning', max_length=20, verbose_name='الحالة')),
                ('beneficiaries_count', models.IntegerField(default=0, verbose_name='عدد المستفيدين')),
                ('locations', models.TextField(blank=True, null=True, verbose_name='مواقع التنفيذ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='آخر تحديث')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='منشأ بواسطة')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مدير المشروع')),
            ],
            options={
                'verbose_name': 'historical مشروع',
                'verbose_name_plural': 'historical المشاريع',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم المشروع')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المشروع')),
                ('project_type', models.CharField(choices=[('food', 'توزيع غذاء'), ('clothing', 'كسوة الشتاء'), ('water', 'سقيا المياه'), ('medical', 'دعم العلاج'), ('renovation', 'ترميم المنازل'), ('educational', 'مساعدات تعليمية'), ('seasonal', 'مساعدات موسمية'), ('iftar', 'إفطار صائم'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الهدف المالي')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي الميزانية')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المنصرف')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('planning', 'تخطيط'), ('approved', 'معتمد'), ('in_progress', 'قيد التنفيذ'), ('completed', 'منتهي'), ('cancelled', 'ملغي')], default='planning', max_length=20, verbose_name='الحالة')),
                ('beneficiaries_count', models.IntegerField(default=0, verbose_name='عدد المستفيدين')),
                ('locations', models.TextField(blank=True, null=True, verbose_name='مواقع التنفيذ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_projects', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='منشأ بواسطة')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='مدير المشروع')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المرحلة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الميزانية')),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المنصرف')),
                ('status', models.CharField(choices=[('pending', 'قادمة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'منجزة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مرحلة مشروع',
                'verbose_name_plural': 'مراحل المشروع',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='projects_pr_code_80abae_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_type'], name='projects_pr_project_573ce6_idx'),
        ),
    ]
