# Generated by Django 6.0.6 on 2026-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['project'], name='projects_pr_project_820c34_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['status'], name='projects_pr_status_44081c_idx'),
        ),
    ]
