# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('donors', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم التبرع')),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المتبرع (للمجهول)')),
                ('donation_type', models.CharField(choices=[('cash', 'نقدي'), ('in_kind', 'عيني'), ('electronic', 'إلكتروني')], max_length=20, verbose_name='نوع التبرع')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('transfer', 'تحويل بنكي'), ('card', 'بطاقة ائتمان'), ('wallet', 'محفظة إلكترونية'), ('cheque', 'شيك')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='الأصناف (للعيني)')),
                ('transaction_type', models.CharField(choices=[('general', 'عام'), ('zakat', 'زكاة'), ('sadaqah', 'صدقة'), ('sponsorship', 'كفالة'), ('project', 'مشروع'), ('endowment', 'وقف')], default='general', max_length=20, verbose_name='نوع المعاملة')),
                ('campaign', models.CharField(blank=True, max_length=255, null=True, verbose_name='الحملة')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإيصال')),
                ('receipt_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإيصال')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='تبرع مجهول')),
                ('is_zakat', models.BooleanField(default=False, verbose_name='زكاة')),
                ('zakat_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الزكاة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('status', models.CharField(choices=[('recorded', 'مسجل'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='recorded', max_length=20, verbose_name='الحالة')),
                ('is_deposited', models.BooleanField(default=False, verbose_name='تم الإيداع')),
                ('deposited_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإيداع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_donations', to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donors.donor', verbose_name='المتبرع')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='projects.project', verbose_name='المشروع')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_donations', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'تبرع',
                'verbose_name_plural': 'التبرعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم الصنف')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('unit', models.CharField(max_length=50, verbose_name='الوحدة')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='القيمة التقديرية')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_items', to='donations.donation', verbose_name='التبرع')),
            ],
            options={
                'verbose_name': 'صنف تبرع',
                'verbose_name_plural': 'أصناف التبرعات',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDonation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='رقم التبرع')),
                ('donor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المتبرع (للمجهول)')),
                ('donation_type', models.CharField(choices=[('cash', 'نقدي'), ('in_kind', 'عيني'), ('electronic', 'إلكتروني')], max_length=20, verbose_name='نوع التبرع')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('transfer', 'تحويل بنكي'), ('card', 'بطاقة ائتمان'), ('wallet', 'محفظة إلكترونية'), ('cheque', 'شيك')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('items', models.JSONField(blank=True, default=list, verbose_name='الأصناف (للعيني)')),
                ('transaction_type', models.CharField(choices=[('general', 'عام'), ('zakat', 'زكاة'), ('sadaqah', 'صدقة'), ('sponsorship', 'كفالة'), ('project', 'مشروع'), ('endowment', 'وقف')], default='general', max_length=20, verbose_name='نوع المعاملة')),
                ('campaign', models.CharField(blank=True, max_length=255, null=True, verbose_name='الحملة')),
                ('receipt_number', models.CharField(db_index=True, max_length=50, verbose_name='رقم الإيصال')),
                ('receipt_date', models.DateField(blank=True, editable=False, verbose_name='تاريخ الإيصال')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='تبرع مجهول')),
                ('is_zakat', models.BooleanField(default=False, verbose_name='زكاة')),
                ('zakat_year', models.IntegerField(blank=True, null=True, verbose_name='سنة الزكاة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('status', models.CharField(choices=[('recorded', 'مسجل'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='recorded', max_length=20, verbose_name='الحالة')),
                ('is_deposited', models.BooleanField(default=False, verbose_name='تم الإيداع')),
                ('deposited_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإيداع')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='آخر تحديث')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة')),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='donors.donor', verbose_name='المتبرع')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='المشروع')),
                ('received_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'historical تبرع',
                'verbose_name_plural': 'historical التبرعات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['code'], name='donations_d_code_fb940b_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['receipt_number'], name='donations_d_receipt_a122f3_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_type'], name='donations_d_donatio_5e5d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['transaction_type'], name='donations_d_transac_d94dec_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['receipt_date'], name='donations_d_receipt_68025e_idx'),
        ),
    ]
