# Generated by Django 6.0.6 on 2026-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donationitem',
            index=models.Index(fields=['donation'], name='donations_d_donatio_902694_idx'),
        ),
    ]
