# Generated by Django 6.0.6 on 2026-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='accounts_us_is_dele_1bd6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['otp_enabled'], name='accounts_us_otp_ena_8c3a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_id_566c09_idx'),
        ),
    ]
