# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('priority', models.IntegerField(default=0, verbose_name='أولوية التواصل')),
            ],
            options={
                'verbose_name': 'تصنيف متبرع',
                'verbose_name_plural': 'تصنيفات المتبرعين',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDonor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='كود المتبرع')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('donor_type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة'), ('organization', 'مؤسسة')], default='individual', max_length=20, verbose_name='النوع')),
                ('phone', models.CharField(max_length=20, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية')),
                ('commercial_reg', models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='شخص التواصل')),
                ('preferred_contact', models.CharField(choices=[('phone', 'اتصال هاتفي'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية')], default='phone', max_length=20, verbose_name='طريقة التواصل')),
                ('preferred_donation', models.CharField(blank=True, choices=[('cash', 'نقدي'), ('in_kind', 'عيني'), ('sponsorship', 'كفالة'), ('project', 'مشروع'), ('zakat', 'زكاة')], max_length=20, null=True, verbose_name='نوع التبرع المفضل')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='متبرع مجهول')),
                ('is_committed', models.BooleanField(default=False, verbose_name='متبرع منتظم')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي التبرعات')),
                ('last_donation_date', models.DateField(blank=True, null=True, verbose_name='آخر تبرع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='آخر تحديث')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة')),
                ('donor_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='donors.donorcategory', verbose_name='التصنيف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical متبرع',
                'verbose_name_plural': 'historical المتبرعين',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المتبرع')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('donor_type', models.CharField(choices=[('individual', 'فرد'), ('company', 'شركة'), ('organization', 'مؤسسة')], default='individual', max_length=20, verbose_name='النوع')),
                ('phone', models.CharField(max_length=20, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية')),
                ('commercial_reg', models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='شخص التواصل')),
                ('preferred_contact', models.CharField(choices=[('phone', 'اتصال هاتفي'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية')], default='phone', max_length=20, verbose_name='طريقة التواصل')),
                ('preferred_donation', models.CharField(blank=True, choices=[('cash', 'نقدي'), ('in_kind', 'عيني'), ('sponsorship', 'كفالة'), ('project', 'مشروع'), ('zakat', 'زكاة')], max_length=20, null=True, verbose_name='نوع التبرع المفضل')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='متبرع مجهول')),
                ('is_committed', models.BooleanField(default=False, verbose_name='متبرع منتظم')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي التبرعات')),
                ('last_donation_date', models.DateField(blank=True, null=True, verbose_name='آخر تبرع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_donors', to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة')),
                ('donor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donors', to='donors.donorcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'متبرع',
                'verbose_name_plural': 'المتبرعين',
                'ordering': ['-total_donations'],
                'indexes': [models.Index(fields=['code'], name='donors_dono_code_572057_idx'), models.Index(fields=['full_name'], name='donors_dono_full_na_9f3576_idx'), models.Index(fields=['phone'], name='donors_dono_phone_2b49f7_idx'), models.Index(fields=['city'], name='donors_dono_city_452b0f_idx')],
            },
        ),
    ]
