# Generated by Django 6.0.6 on 2026-06-28 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='city',
            field=models.CharField(blank=True, choices=[('', '-- اختر المحافظة --'), ('cairo', 'القاهرة'), ('alexandria', 'الإسكندرية'), ('giza', 'الجيزة'), ('sharqia', 'الشرقية'), ('dakahlia', 'الدقهلية'), ('beheira', 'البحيرة'), ('gharbia', 'الغربية'), ('monufia', 'المنوفية'), ('qalyubia', 'القليوبية'), ('damietta', 'دمياط'), ('port_said', 'بورسعيد'), ('suez', 'السويس'), ('ismailia', 'الإسماعيلية'), ('kafr_sheikh', 'كفر الشيخ'), ('fayoum', 'الفيوم'), ('b_sweif', 'بني سويف'), ('menya', 'المنيا'), ('asyut', 'أسيوط'), ('sohag', 'سوهاج'), ('qena', 'قنا'), ('luxor', 'الأقصر'), ('aswan', 'أسوان'), ('red_sea', 'البحر الأحمر'), ('wadi_gedid', 'الوادي الجديد'), ('matrouh', 'مطروح'), ('north_sinai', 'شمال سيناء'), ('south_sinai', 'جنوب سيناء'), ('outside', 'خارج مصر')], max_length=100, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقمًا', regex='^[0-9]{14}$')], verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري من 11 رقم مثال: 01234567890', regex='^01[0-9]{9}$')], verbose_name='رقم الموبايل'),
        ),
        migrations.AlterField(
            model_name='historicaldonor',
            name='city',
            field=models.CharField(blank=True, choices=[('', '-- اختر المحافظة --'), ('cairo', 'القاهرة'), ('alexandria', 'الإسكندرية'), ('giza', 'الجيزة'), ('sharqia', 'الشرقية'), ('dakahlia', 'الدقهلية'), ('beheira', 'البحيرة'), ('gharbia', 'الغربية'), ('monufia', 'المنوفية'), ('qalyubia', 'القليوبية'), ('damietta', 'دمياط'), ('port_said', 'بورسعيد'), ('suez', 'السويس'), ('ismailia', 'الإسماعيلية'), ('kafr_sheikh', 'كفر الشيخ'), ('fayoum', 'الفيوم'), ('b_sweif', 'بني سويف'), ('menya', 'المنيا'), ('asyut', 'أسيوط'), ('sohag', 'سوهاج'), ('qena', 'قنا'), ('luxor', 'الأقصر'), ('aswan', 'أسوان'), ('red_sea', 'البحر الأحمر'), ('wadi_gedid', 'الوادي الجديد'), ('matrouh', 'مطروح'), ('north_sinai', 'شمال سيناء'), ('south_sinai', 'جنوب سيناء'), ('outside', 'خارج مصر')], max_length=100, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='historicaldonor',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يتكون من 14 رقمًا', regex='^[0-9]{14}$')], verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='historicaldonor',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري من 11 رقم مثال: 01234567890', regex='^01[0-9]{9}$')], verbose_name='رقم الموبايل'),
        ),
    ]
