# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSponsorship',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='رقم الكفالة')),
                ('sponsorship_type', models.CharField(choices=[('orphan', 'كفالة يتيم'), ('family', 'كفالة أسرة'), ('patient', 'كفالة مريض'), ('student', 'كفالة طالب علم')], max_length=20, verbose_name='نوع الكفالة')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الشهري')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('duration_months', models.IntegerField(default=12, verbose_name='المدة (شهر)')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='مستمرة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('transfer', 'تحويل بنكي'), ('automatic', 'خصم آلي'), ('card', 'بطاقة')], default='transfer', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_day', models.IntegerField(default=1, verbose_name='يوم الدفع')),
                ('is_active', models.BooleanField(default=True, verbose_name='سارية')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('paused', 'متوقفة'), ('expired', 'منتهية'), ('cancelled', 'ملغاة')], default='active', max_length=20, verbose_name='الحالة')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='آخر صرف')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف القادم')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المدفوع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='آخر تحديث')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('beneficiary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beneficiaries.beneficiary', verbose_name='المستفيد')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='منشأ بواسطة')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='donors.donor', verbose_name='الكفيل')),
            ],
            options={
                'verbose_name': 'historical كفالة',
                'verbose_name_plural': 'historical الكفالات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم الكفالة')),
                ('sponsorship_type', models.CharField(choices=[('orphan', 'كفالة يتيم'), ('family', 'كفالة أسرة'), ('patient', 'كفالة مريض'), ('student', 'كفالة طالب علم')], max_length=20, verbose_name='نوع الكفالة')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الشهري')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('duration_months', models.IntegerField(default=12, verbose_name='المدة (شهر)')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='مستمرة')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('transfer', 'تحويل بنكي'), ('automatic', 'خصم آلي'), ('card', 'بطاقة')], default='transfer', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_day', models.IntegerField(default=1, verbose_name='يوم الدفع')),
                ('is_active', models.BooleanField(default=True, verbose_name='سارية')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('paused', 'متوقفة'), ('expired', 'منتهية'), ('cancelled', 'ملغاة')], default='active', max_length=20, verbose_name='الحالة')),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='آخر صرف')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصرف القادم')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='إجمالي المدفوع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='beneficiaries.beneficiary', verbose_name='المستفيد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='منشأ بواسطة')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='donors.donor', verbose_name='الكفيل')),
            ],
            options={
                'verbose_name': 'كفالة',
                'verbose_name_plural': 'الكفالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorshipPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('month', models.IntegerField(verbose_name='الشهر')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('is_donor_paid', models.BooleanField(default=True, verbose_name='تم الدفع من الكفيل')),
                ('is_beneficiary_received', models.BooleanField(default=False, verbose_name='استلم المستفيد')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإيصال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة')),
                ('sponsorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sponsorships.sponsorship', verbose_name='الكفالة')),
            ],
            options={
                'verbose_name': 'دفعة كفالة',
                'verbose_name_plural': 'دفعات الكفالات',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='sponsorship',
            index=models.Index(fields=['code'], name='sponsorship_code_76b660_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorship',
            index=models.Index(fields=['sponsorship_type'], name='sponsorship_sponsor_7a7df1_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorship',
            index=models.Index(fields=['status'], name='sponsorship_status_674900_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorshippayment',
            unique_together={('sponsorship', 'month', 'year')},
        ),
    ]
