# Generated by Django 6.0.6 on 2026-07-08 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sponsorshippayment',
            index=models.Index(fields=['sponsorship'], name='sponsorship_sponsor_bab04d_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsorshippayment',
            index=models.Index(fields=['payment_date'], name='sponsorship_payment_f90608_idx'),
        ),
    ]
