# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('donations', '0001_initial'),
        ('donors', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255, verbose_name='اسم البنك')),
                ('account_name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('account_number', models.CharField(max_length=50, verbose_name='رقم الحساب')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('account_type', models.CharField(choices=[('current', 'جاري'), ('savings', 'استثماري')], default='current', max_length=20, verbose_name='النوع')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حساب بنكي',
                'verbose_name_plural': 'الحسابات البنكية',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الحساب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('main', 'رئيسي'), ('sub', 'فرعي')], max_length=20, verbose_name='النوع')),
                ('account_group', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('income', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, verbose_name='المجموعة')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الافتتاحي')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.expensecategory', verbose_name='التصنيف الأب')),
            ],
            options={
                'verbose_name': 'تصنيف مصروف',
                'verbose_name_plural': 'تصنيفات المصروفات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFinancialEntry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='رقم القيد')),
                ('entry_type', models.CharField(choices=[('income', 'إيراد'), ('expense', 'مصروف'), ('transfer', 'تحويل')], max_length=20, verbose_name='نوع القيد')),
                ('entry_date', models.DateField(verbose_name='تاريخ القيد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('description', models.TextField(verbose_name='البيان')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('transfer', 'تحويل بنكي'), ('card', 'بطاقة'), ('cheque', 'شيك')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم مرجعي')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإيصال')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('transaction_type', models.CharField(choices=[('general', 'عام'), ('zakat', 'زكاة'), ('sadaqah', 'صدقة'), ('sponsorship', 'كفالة'), ('project', 'مشروع')], default='general', max_length=20, verbose_name='نوع المعاملة الشرعية')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='تمت التسوية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.account', verbose_name='الحساب')),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('bank_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.bankaccount', verbose_name='حساب بنكي')),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.case', verbose_name='حالة')),
                ('donation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='donations.donation', verbose_name='تبرع')),
                ('donor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='donors.donor', verbose_name='متبرع')),
                ('expense_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.expensecategory', verbose_name='تصنيف المصروف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project', verbose_name='مشروع')),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المسجل')),
            ],
            options={
                'verbose_name': 'historical قيد مالي',
                'verbose_name_plural': 'historical القيود المالية',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم القيد')),
                ('entry_type', models.CharField(choices=[('income', 'إيراد'), ('expense', 'مصروف'), ('transfer', 'تحويل')], max_length=20, verbose_name='نوع القيد')),
                ('entry_date', models.DateField(verbose_name='تاريخ القيد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('description', models.TextField(verbose_name='البيان')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('transfer', 'تحويل بنكي'), ('card', 'بطاقة'), ('cheque', 'شيك')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم مرجعي')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الإيصال')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد')),
                ('transaction_type', models.CharField(choices=[('general', 'عام'), ('zakat', 'زكاة'), ('sadaqah', 'صدقة'), ('sponsorship', 'كفالة'), ('project', 'مشروع')], default='general', max_length=20, verbose_name='نوع المعاملة الشرعية')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='تمت التسوية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.account', verbose_name='الحساب')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.bankaccount', verbose_name='حساب بنكي')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='cases.case', verbose_name='حالة')),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='donations.donation', verbose_name='تبرع')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='donors.donor', verbose_name='متبرع')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='finance.expensecategory', verbose_name='تصنيف المصروف')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='projects.project', verbose_name='مشروع')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_entries', to=settings.AUTH_USER_MODEL, verbose_name='المسجل')),
            ],
            options={
                'verbose_name': 'قيد مالي',
                'verbose_name_plural': 'القيود المالية',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['code'], name='finance_fin_code_bd3304_idx'), models.Index(fields=['entry_type'], name='finance_fin_entry_t_296ed9_idx'), models.Index(fields=['entry_date'], name='finance_fin_entry_d_91672d_idx'), models.Index(fields=['transaction_type'], name='finance_fin_transac_80f3e1_idx')],
            },
        ),
    ]
