# Generated by Django 6.0.6 on 2026-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_active'], name='finance_ban_is_acti_f2dd58_idx'),
        ),
    ]
