# Generated by Django 6.0.6 on 2026-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bankaccount_finance_ban_is_acti_f2dd58_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialentry',
            name='currency',
            field=models.CharField(default='EGP', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialentry',
            name='currency',
            field=models.CharField(default='EGP', max_length=3, verbose_name='العملة'),
        ),
    ]
