# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication_type', models.CharField(choices=[('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('call', 'مكالمة')], max_length=20, verbose_name='النوع')),
                ('direction', models.CharField(choices=[('incoming', 'وارد'), ('outgoing', 'صادر')], default='outgoing', max_length=20, verbose_name='الاتجاه')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='الموضوع')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('recipient', models.CharField(max_length=255, verbose_name='المستلم')),
                ('related_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='العنصر المرتبط')),
                ('related_id', models.UUIDField(blank=True, null=True, verbose_name='معرف العنصر')),
                ('status', models.CharField(choices=[('sent', 'مرسلة'), ('delivered', 'تم الاستلام'), ('read', 'مقروءة'), ('failed', 'فشلت')], default='sent', max_length=20, verbose_name='الحالة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='beneficiaries.beneficiary', verbose_name='مستفيد')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='donors.donor', verbose_name='متبرع')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'مراسلة',
                'verbose_name_plural': 'المراسلات',
                'ordering': ['-sent_at'],
            },
        ),
    ]
