# Generated by Django 6.0.6 on 2026-07-08 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_alter_beneficiary_city_alter_beneficiary_district_and_more'),
        ('communications', '0001_initial'),
        ('donors', '0002_alter_donor_city_alter_donor_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['sender'], name='communicati_sender__9bbbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['beneficiary'], name='communicati_benefic_139189_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['donor'], name='communicati_donor_i_f71b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['status'], name='communicati_status_4c900b_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['sent_at'], name='communicati_sent_at_c2be0f_idx'),
        ),
    ]
