# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم الحالة')),
                ('case_type', models.CharField(choices=[('financial', 'مساعدات مالية'), ('food', 'مساعدات غذائية'), ('cloth', 'كسوة'), ('medical', 'علاج'), ('educational', 'مساعدات تعليمية'), ('housing', 'ترميم/إسكان'), ('emergency', 'طارئة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المساعدة')),
                ('priority', models.CharField(choices=[('urgent', 'عاجلة'), ('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('description', models.TextField(verbose_name='وصف الحالة')),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ المطلوب')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ المعتمد')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('under_study', 'قيد الدراسة'), ('approved', 'معتمد'), ('disbursed', 'تم الصرف'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], default='new', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('close_reason', models.TextField(blank=True, null=True, verbose_name='سبب الإغلاق')),
                ('needs_reassessment', models.BooleanField(default=False, verbose_name='يحتاج إعادة تقييم')),
                ('reassessment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إعادة التقييم')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cases', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='المسند إلى')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='beneficiaries.beneficiary', verbose_name='المستفيد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='منشأ بواسطة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
            options={
                'verbose_name': 'حالة',
                'verbose_name_plural': 'الحالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=50, verbose_name='نوع النشاط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('old_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='الحالة القديمة')),
                ('new_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='الحالة الجديدة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشاط')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cases.case', verbose_name='الحالة')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='منفذ النشاط')),
            ],
            options={
                'verbose_name': 'نشاط حالة',
                'verbose_name_plural': 'نشاطات الحالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='الخاصية')),
                ('value', models.TextField(verbose_name='القيمة')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cases.case', verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'خاصية حالة',
                'verbose_name_plural': 'خصائص الحالات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='cases/', verbose_name='الصورة')),
                ('label', models.CharField(max_length=100, verbose_name='تسمية الصورة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.case', verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'صورة حالة',
                'verbose_name_plural': 'صور الحالات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCase',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='رقم الحالة')),
                ('case_type', models.CharField(choices=[('financial', 'مساعدات مالية'), ('food', 'مساعدات غذائية'), ('cloth', 'كسوة'), ('medical', 'علاج'), ('educational', 'مساعدات تعليمية'), ('housing', 'ترميم/إسكان'), ('emergency', 'طارئة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المساعدة')),
                ('priority', models.CharField(choices=[('urgent', 'عاجلة'), ('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('description', models.TextField(verbose_name='وصف الحالة')),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ المطلوب')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ المعتمد')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('under_study', 'قيد الدراسة'), ('approved', 'معتمد'), ('disbursed', 'تم الصرف'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], default='new', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('close_reason', models.TextField(blank=True, null=True, verbose_name='سبب الإغلاق')),
                ('needs_reassessment', models.BooleanField(default=False, verbose_name='يحتاج إعادة تقييم')),
                ('reassessment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إعادة التقييم')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='آخر تحديث')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المعتمد')),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المسند إلى')),
                ('beneficiary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beneficiaries.beneficiary', verbose_name='المستفيد')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='منشأ بواسطة')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='المراجع')),
            ],
            options={
                'verbose_name': 'historical حالة',
                'verbose_name_plural': 'historical الحالات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['code'], name='cases_case_code_36365a_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='cases_case_priorit_474e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_type'], name='cases_case_case_ty_2efb82_idx'),
        ),
    ]
