# Generated by Django 6.0.6 on 2026-07-08 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_add_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='caseactivity',
            index=models.Index(fields=['case'], name='cases_casea_case_id_be8caa_idx'),
        ),
        migrations.AddIndex(
            model_name='casefeature',
            index=models.Index(fields=['case'], name='cases_casef_case_id_08b964_idx'),
        ),
        migrations.AddIndex(
            model_name='caseimage',
            index=models.Index(fields=['case'], name='cases_casei_case_id_700bdb_idx'),
        ),
    ]
