# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم الوثيقة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('document_type', models.CharField(choices=[('id', 'هوية'), ('report', 'تقرير'), ('contract', 'عقد'), ('receipt', 'إيصال'), ('photo', 'صورة'), ('medical', 'تقرير طبي'), ('study', 'دراسة حالة'), ('other', 'أخرى')], max_length=20, verbose_name='النوع')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='الملف')),
                ('file_size', models.IntegerField(default=0, verbose_name='حجم الملف')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الملف')),
                ('related_model', models.CharField(max_length=50, verbose_name='النموذج المرتبط')),
                ('related_id', models.UUIDField(verbose_name='معرف العنصر')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='سري')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الرافع')),
            ],
            options={
                'verbose_name': 'وثيقة',
                'verbose_name_plural': 'الوثائق',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['related_model', 'related_id'], name='documents_d_related_760f27_idx')],
            },
        ),
    ]
