# Generated by Django 6.0.6 on 2026-07-08 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_alter_beneficiary_city_alter_beneficiary_district_and_more'),
        ('cases', '0003_caseactivity_cases_casea_case_id_be8caa_idx_and_more'),
        ('donations', '0002_donationitem_donations_d_donatio_902694_idx'),
        ('inventory', '0001_initial'),
        ('projects', '0002_projectphase_projects_pr_project_820c34_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['item'], name='inventory_i_item_id_a5cd26_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_i_transac_2eccee_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['created_at'], name='inventory_i_created_670884_idx'),
        ),
    ]
