# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المناسبة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('support_type', models.CharField(choices=[('food', 'دعم غذائي'), ('financial', 'دعم مالي'), ('cloth', 'كسوة'), ('medical', 'علاج'), ('educational', 'دعم تعليمي'), ('housing', 'ترميم/إسكان'), ('other', 'أخرى')], default='food', max_length=50, verbose_name='نوع الدعم')),
                ('custom_support_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع الدعم (مخصص)')),
                ('budget_enabled', models.BooleanField(default=False, verbose_name='بميزانية')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الميزانية')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='موسم سنوي')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('completed', 'منتهي'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_occasions', to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
            ],
            options={
                'verbose_name': 'مناسبة',
                'verbose_name_plural': 'المناسبات والمواسم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OccasionMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_type', models.CharField(choices=[('case', 'حالة'), ('beneficiary', 'مستفيد')], max_length=20, verbose_name='النوع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('completed', models.BooleanField(default=False, verbose_name='تم')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occasion_members', to='beneficiaries.beneficiary', verbose_name='المستفيد')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occasion_members', to='cases.case', verbose_name='الحالة')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='occasions.occasion', verbose_name='المناسبة')),
            ],
            options={
                'verbose_name': 'عضو مناسبة',
                'verbose_name_plural': 'أعضاء المناسبات',
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='OccasionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255, verbose_name='المهمة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'تم'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='أنجز بواسطة')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='occasions.occasionmember', verbose_name='العضو')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['created_at'],
            },
        ),
    ]
