# Generated by Django 6.0.6 on 2026-07-08 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_alter_beneficiary_city_alter_beneficiary_district_and_more'),
        ('cases', '0003_caseactivity_cases_casea_case_id_be8caa_idx_and_more'),
        ('occasions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='occasion',
            index=models.Index(fields=['status'], name='occasions_o_status_319b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='occasion',
            index=models.Index(fields=['support_type'], name='occasions_o_support_409d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='occasionmember',
            index=models.Index(fields=['occasion'], name='occasions_o_occasio_cd1175_idx'),
        ),
        migrations.AddIndex(
            model_name='occasionmember',
            index=models.Index(fields=['member_type'], name='occasions_o_member__510224_idx'),
        ),
        migrations.AddIndex(
            model_name='occasionmember',
            index=models.Index(fields=['completed'], name='occasions_o_complet_36f395_idx'),
        ),
        migrations.AddIndex(
            model_name='occasiontask',
            index=models.Index(fields=['member'], name='occasions_o_member__54e392_idx'),
        ),
        migrations.AddIndex(
            model_name='occasiontask',
            index=models.Index(fields=['status'], name='occasions_o_status_95f9ba_idx'),
        ),
    ]
