# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف')),
                ('status', models.CharField(choices=[('success', 'نجاح'), ('failed', 'فشل')], max_length=20, verbose_name='الحالة')),
                ('backup_type', models.CharField(choices=[('auto', 'تلقائي'), ('manual', 'يدوي')], default='auto', max_length=20, verbose_name='النوع')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مسار الحفظ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سجل نسخ احتياطي',
                'verbose_name_plural': 'سجلات النسخ الاحتياطي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('notification_type', models.CharField(choices=[('info', 'معلومات'), ('success', 'نجاح'), ('warning', 'تنبيه'), ('error', 'خطأ')], default='info', max_length=20, verbose_name='النوع')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('related_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='النموذج المرتبط')),
                ('related_id', models.UUIDField(blank=True, null=True, verbose_name='معرف العنصر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.JSONField(verbose_name='القيمة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='مشفر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'إعداد النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('view', 'قراءة'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('approve', 'اعتماد'), ('reject', 'رفض'), ('disburse', 'صرف'), ('export', 'تصدير')], max_length=20, verbose_name='الإجراء')),
                ('model_name', models.CharField(max_length=100, verbose_name='اسم النموذج')),
                ('model_id', models.UUIDField(db_index=True, verbose_name='معرف العنصر')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='المتصفح')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='الوقت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['model_name', 'model_id'], name='audit_audit_model_n_0d48bd_idx')],
            },
        ),
    ]
