# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='كود الموظف')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('employee_type', models.CharField(choices=[('employee', 'موظف'), ('volunteer', 'متطوع')], max_length=20, verbose_name='النوع')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='المسمى الوظيفي')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='القسم')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('contract_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('volunteer', 'متطوع')], default='full_time', max_length=20, verbose_name='نوع العقد')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب')),
                ('phone', models.CharField(max_length=20, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='للطوارئ')),
                ('qualifications', models.TextField(blank=True, null=True, verbose_name='المؤهلات')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='المهارات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='branches.branch', verbose_name='الفرع')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب النظام')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('mission', 'مأمورية')], default='present', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'الحضور والانصراف',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('employee_code', models.CharField(db_index=True, max_length=20, verbose_name='كود الموظف')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('employee_type', models.CharField(choices=[('employee', 'موظف'), ('volunteer', 'متطوع')], max_length=20, verbose_name='النوع')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='المسمى الوظيفي')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='القسم')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('contract_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('volunteer', 'متطوع')], default='full_time', max_length=20, verbose_name='نوع العقد')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب')),
                ('phone', models.CharField(max_length=20, verbose_name='الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='للطوارئ')),
                ('qualifications', models.TextField(blank=True, null=True, verbose_name='المؤهلات')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='المهارات')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch', verbose_name='الفرع')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='حساب النظام')),
            ],
            options={
                'verbose_name': 'historical موظف',
                'verbose_name_plural': 'historical الموظفين',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('high', 'عالية'), ('medium', 'متوسطة'), ('low', 'منخفضة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'منجزة'), ('cancelled', 'ملغاة')], default='new', max_length=20, verbose_name='الحالة')),
                ('related_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='النموذج المرتبط')),
                ('related_id', models.UUIDField(blank=True, null=True, verbose_name='معرف العنصر')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مسند من')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_code'], name='employees_e_employe_f8cfea_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['full_name'], name='employees_e_full_na_997ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_type'], name='employees_e_employe_60d814_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
