# Generated by Django 6.0.6 on 2026-06-28 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري من 11 رقم مثال: 01234567890', regex='^01[0-9]{9}$')], verbose_name='رقم الموبايل'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري من 11 رقم مثال: 01234567890', regex='^01[0-9]{9}$')], verbose_name='رقم الموبايل'),
        ),
    ]
