# Generated by Django 6.0.6 on 2026-07-08 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_attendance_employees_a_date_b8bb7b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري: 01234567890 أو +201234567890', regex='^(\\+20|0)1[0-9]{9}$')], verbose_name='رقم الموبايل'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري: 01234567890 أو +201234567890', regex='^(\\+20|0)1[0-9]{9}$')], verbose_name='رقم الموبايل'),
        ),
    ]
