# Generated by Django 6.0.6 on 2026-06-19 22:42

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBeneficiary',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='كود المستفيد')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='جوال آخر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'أعزب/عزباء'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=20, null=True, verbose_name='الحالة الاجتماعية')),
                ('family_members', models.IntegerField(default=1, verbose_name='عدد أفراد الأسرة')),
                ('has_orphans', models.BooleanField(default=False, verbose_name='يوجد أيتام')),
                ('orphans_count', models.IntegerField(default=0, verbose_name='عدد الأيتام')),
                ('health_status', models.TextField(blank=True, null=True, verbose_name='الحالة الصحية')),
                ('has_chronic_disease', models.BooleanField(default=False, verbose_name='أمراض مزمنة')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='تفاصيل الأمراض')),
                ('has_disabilities', models.BooleanField(default=False, verbose_name='إعاقات')),
                ('disabilities_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل الإعاقات')),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'موظف'), ('unemployed', 'عاطل'), ('retired', 'متقاعد'), ('student', 'طالب'), ('disabled', 'عاجز عن العمل')], max_length=20, null=True, verbose_name='الوضع الوظيفي')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الدخل الشهري')),
                ('housing_type', models.CharField(blank=True, choices=[('owned', 'ملك'), ('rented', 'إيجار'), ('relative', 'مع أقارب'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='نوع السكن')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='حالة عاجلة')),
                ('priority_score', models.IntegerField(default=0, verbose_name='درجة الأولوية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('closed', 'مغلق')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='آخر تحديث')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical مستفيد',
                'verbose_name_plural': 'historical المستفيدين',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المستفيد')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهوية')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='جوال آخر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='الحي')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'أعزب/عزباء'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=20, null=True, verbose_name='الحالة الاجتماعية')),
                ('family_members', models.IntegerField(default=1, verbose_name='عدد أفراد الأسرة')),
                ('has_orphans', models.BooleanField(default=False, verbose_name='يوجد أيتام')),
                ('orphans_count', models.IntegerField(default=0, verbose_name='عدد الأيتام')),
                ('health_status', models.TextField(blank=True, null=True, verbose_name='الحالة الصحية')),
                ('has_chronic_disease', models.BooleanField(default=False, verbose_name='أمراض مزمنة')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='تفاصيل الأمراض')),
                ('has_disabilities', models.BooleanField(default=False, verbose_name='إعاقات')),
                ('disabilities_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل الإعاقات')),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'موظف'), ('unemployed', 'عاطل'), ('retired', 'متقاعد'), ('student', 'طالب'), ('disabled', 'عاجز عن العمل')], max_length=20, null=True, verbose_name='الوضع الوظيفي')),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الدخل الشهري')),
                ('housing_type', models.CharField(blank=True, choices=[('owned', 'ملك'), ('rented', 'إيجار'), ('relative', 'مع أقارب'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='نوع السكن')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='حالة عاجلة')),
                ('priority_score', models.IntegerField(default=0, verbose_name='درجة الأولوية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'موقوف'), ('closed', 'مغلق')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='المرفقات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='branches.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beneficiaries', to=settings.AUTH_USER_MODEL, verbose_name='مسجل بواسطة')),
            ],
            options={
                'verbose_name': 'مستفيد',
                'verbose_name_plural': 'المستفيدين',
                'ordering': ['-priority_score', '-created_at'],
                'indexes': [models.Index(fields=['code'], name='beneficiari_code_c3b043_idx'), models.Index(fields=['full_name'], name='beneficiari_full_na_1d3b7b_idx'), models.Index(fields=['phone'], name='beneficiari_phone_bcff47_idx'), models.Index(fields=['city'], name='beneficiari_city_f56396_idx'), models.Index(fields=['status'], name='beneficiari_status_ff1fe1_idx'), models.Index(fields=['is_urgent'], name='beneficiari_is_urge_b1f412_idx')],
            },
        ),
    ]
