# Generated by Django 6.0.6 on 2026-07-08 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_alter_beneficiary_city_alter_beneficiary_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري: 01234567890 أو +201234567890', regex='^(\\+20|0)1[0-9]{9}$')], verbose_name='رقم الموبايل'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري: 01234567890 أو +201234567890', regex='^(\\+20|0)1[0-9]{9}$')], verbose_name='موبايل آخر'),
        ),
        migrations.AlterField(
            model_name='historicalbeneficiary',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري: 01234567890 أو +201234567890', regex='^(\\+20|0)1[0-9]{9}$')], verbose_name='رقم الموبايل'),
        ),
        migrations.AlterField(
            model_name='historicalbeneficiary',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='رقم الموبايل المصري: 01234567890 أو +201234567890', regex='^(\\+20|0)1[0-9]{9}$')], verbose_name='موبايل آخر'),
        ),
    ]
